apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-springboot-tzbkxhpt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: tssc-quay-quay-tssc-quay.apps.cluster-bnl5f.bnl5f.sandbox1132.opentlc.com/tssc/java-springboot-tzbkxhpt:bdcc12c0bfd1667e4faf51e58ca688168234e79e@sha256:9015cf2755b85199fd581012c5961b0637b4de35a2b9a4d5266d08b77d5e64c0
          name: container-image
